version: '3'

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    image: chinook_mysql
    container_name: ${DOCKER_COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3307"
      - "33070:33070"
    volumes:
      - "mysql_data:/var/lib/mysql"
    # networks:
    #   - chinook_network
    restart: always

volumes:
  mysql_data:
    driver: local
